.github/workflows/dockerhub.yml

feat: push container image to docker hub

---

.changeset/spotty-hats-glow.md
packages/caravan-wallets/src/ledger.ts

applying changes from https://github.com/unchained-capital/unchained-wallets/pull/140

chore: Future-proof legacy version checking for Ledger bitcoin app

---

.github/workflows/dockerhub.yml

Just push latest, we can add the metadata back later.

fix: fix container tags

---

.github/workflows/dockerhub.yml

Create amd64 and arm64 multiarch image.
Only create new images when coordinator tags are created.

feat: amd64 and arm64 images

---

.changeset/clean-lamps-develop.md
.changeset/tricky-stingrays-rest.md
apps/coordinator/src/actions/clientActions.ts
apps/coordinator/src/components/ClientPicker/index.jsx
apps/coordinator/src/components/Wallet/WalletDescriptorImporter.tsx
apps/coordinator/src/components/Wallet/WalletGenerator.jsx
apps/coordinator/src/components/Wallet/index.jsx
apps/coordinator/src/selectors/wallet.js
packages/caravan-clients/src/client.test.ts
packages/caravan-clients/src/client.ts

Should improve performance when using public client options.

Mempool client fix

---

.github/workflows/deploy.yml
.github/workflows/dockerhub.yml

fix glob pattern

---

README.md
apps/coordinator/Dockerfile
package-lock.json
package.json
packages/caravan-wallets/src/trezor.ts

Fix the build for coordinator.

fix: coordinator build working after rename

---

.changeset/config.json
.github/workflows/release.yml
package.json

Use changeset to version and tag `coordinator` and outlined on:
https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md

Use changeset to version and tag `coordinator`

---

.changeset/pink-paws-give.md
apps/coordinator/src/components/CreateAddress/HardwareWalletPublicKeyImporter.jsx

fix interactions call in HardwareWalletPublicKeyImporter.
Fixes #72

Fix error on address generator

---

packages/bip32/package.json
packages/typescript-config/base.json

Might have needed this to publish from local (first time needs it because of scoped packages defaulting to "private")

tweak to package.json

---

apps/coordinator/src/components/Wallet/index.jsx

Add sparrow to allowed method of importing pubkeys

---

.changeset/selfish-dodos-cheer.md
apps/coordinator/src/components/Wallet/TransactionsTab/hooks.ts
apps/coordinator/src/components/Wallet/TransactionsTab/index.tsx
apps/coordinator/src/components/Wallet/WalletControl.jsx

- Remove Typography header to clean up UI
- Comment out unused code related to confirmed transactions
cc @bucko13

UI cleanup: Remove redundant header and focus on pending transactions

---

apps/coordinator/README.md

I faced some issues while setting up the ngnix 
, for the silicon macbooks have different file structure
, i have updated in the readme

chore: updated readme

---

packages/caravan-health/jest.config.js
packages/caravan-health/package.json
packages/caravan-health/src/__tests__/privacy.test.ts
packages/caravan-health/src/__tests__/wallet.test.ts
packages/caravan-health/src/__tests__/waste.test.ts

[Test]: Jest to Vitest migration `caravan-health` package

---

apps/coordinator/CHANGELOG.md
apps/coordinator/README.md
apps/coordinator/package.json
apps/coordinator/src/components/Wallet/TransactionsTab/TransactionsTable.tsx
apps/coordinator/src/components/Wallet/TransactionsTab/hooks.ts
apps/coordinator/src/components/Wallet/TransactionsTab/index.tsx
apps/coordinator/src/components/Wallet/TransactionsTab/types.ts
apps/coordinator/src/components/Wallet/WalletControl.jsx
package-lock.json
packages/caravan-bitcoin/src/__tests__/psbtv2.test.ts
packages/caravan-clients/CHANGELOG.md
packages/caravan-clients/package.json
packages/caravan-clients/src/__tests__/client.test.ts
packages/caravan-clients/src/__tests__/wallet.test.ts
packages/caravan-clients/src/client.ts
packages/caravan-clients/src/types.ts
packages/caravan-clients/src/wallet.ts
packages/caravan-psbt/CHANGELOG.md
packages/caravan-psbt/package.json
packages/caravan-wallets/src/bitbox.ts

PR to resolve merge conflicts of `vite-migration` and main branch.
related to #187 
cc: @bucko13

vite-migration branch merge conflicts resolved (3)

---

apps/coordinator/src/components/CreateAddress/TextPublicKeyImporter.jsx

**Fixes** : #214 
This pull request includes a change to the `TextPublicKeyImporter` component in the `CreateAddress` module. The change improves the handling of the public key input by ensuring the validation uses the updated value immediately.
* [`apps/coordinator/src/components/CreateAddress/TextPublicKeyImporter.jsx`](diffhunk://#diff-f769278181f07485c6ce7b76ac70e9576b495e6f8e63afbf429891dd190fc56eL26-R28): Modified the `handleChange` function to validate the new public key value directly from the event target, ensuring accurate validation.

Fixed updating of public key value in input format

---

.changeset/honest-trainers-tan.md
package-lock.json
packages/caravan-psbt/package.json

better dep support so that min version is enforced but monorepo deps leveraged.

fix(psbt): 

---

package-lock.json
packages/caravan-clients/.eslintrc.js
packages/caravan-clients/jest.config.js
packages/caravan-clients/package.json
packages/caravan-clients/src/bitcoind.ts
packages/caravan-clients/src/blockExplorer.ts
packages/caravan-clients/src/blockchain.ts
packages/caravan-clients/src/client.test.ts
packages/caravan-clients/src/client.ts
packages/caravan-clients/src/types.ts
packages/caravan-clients/src/wallet.test.ts
packages/caravan-clients/src/wallet.ts
packages/caravan-clients/vitest.config.ts

This PR migrates the `@caravan/caravan-client` test cases from jest to vitest

Migrates `@caravan/caravan-client` tests to vitest

---

.changeset/spotty-tips-vanish.md
apps/coordinator/src/components/LandingNav.tsx
apps/coordinator/src/components/Navbar.jsx

Bugfix for an import error occurring in the build script
**Summary**
I introduced a bug and this will fix it I believe
**Does this PR introduce a breaking change?**
**Other information**
**Have you read the [contributing guide](https://github.com/caravan-bitcoin/caravan/blob/main/apps/coordinator/CONTRIBUTING.md)?**
**For information on creating and using changesets, please refer to our [documentation on changesets](https://github.com/caravan-bitcoin/caravan?tab=readme-ov-file#changesets)**.

Fix: import error in build script

---

.changeset/orange-jokes-run.md
packages/caravan-bitcoin/src/fees.test.ts
packages/caravan-bitcoin/src/p2sh.test.ts
packages/caravan-bitcoin/src/p2sh.ts
packages/caravan-fees/src/tests/transactionAnalyzer.fixtures.ts

Adjusts P2SH output vbyte estimation to account for a fixed length script hash 
Reference Optech Transaction Calculator
https://bitcoinops.org/en/tools/calc-size/#output
A P2SH output consists of the following stack elements
- amount (8 bytes)
- scriptPubKey length (compactSize)
- scriptPubKey (23)
`OP_HASH160 OP_PUSH20 <script_hash> OP_EQUAL`
Regardless of the quorum shape, the `script_hash` will be a sequence of 20 bytes (160 bits). Accordingly the scriptPubKey length only needs to be 1 byte, since 23 < 252.
**Issue Number:**
Fixes #
**Snapshots/Videos:**
**If relevant, did you update the documentation?**
**Summary**
**Does this PR introduce a breaking change?**
**Other information**
**Have you read the [contributing …

fix: P2SH output vbyte estimation

---

.changeset/breezy-dolls-grin.md
package-lock.json
packages/caravan-wallets/package.json
packages/caravan-wallets/src/trezor.ts

Bump @trezor/connect-web -> 9.6.0  to consume bug fixes that will streamline communication with trezor bridge. 
Namely 
> 9.5.4
> - fixing session releasing on page unload (6d01d78)
>
> 9.5.1
> - don't cancel preventively on T1 in certain cases (bf6d9ff)
Supplies required field `appName` in TrezorConnect manifest
**Issue Number:**
Fixes #
**Snapshots/Videos:**
**If relevant, did you update the documentation?**
**Summary**
**Does this PR introduce a breaking change?**
https://github.com/trezor/trezor-suite/blob/develop/packages/connect/CHANGELOG.md
**Other information**
**Have you read the [contributing guide](https://github.com/caravan-bitcoin/caravan/blob/main/apps/coordinator/CONTRIBUTING.md)?**
**For information on creating and using …

Bump @trezor/connect-web to 9.6.0

---

.changeset/small-melons-sneeze.md
apps/coordinator/src/actions/clientActions.ts
apps/coordinator/src/components/ClientPicker/index.jsx
apps/coordinator/src/components/NetworkPicker.jsx
apps/coordinator/src/components/Wallet/ExtendedPublicKeyImporter.jsx
apps/coordinator/src/components/Wallet/TransactionsTab/hooks.ts
apps/coordinator/src/hooks/client.ts
apps/coordinator/src/selectors/wallet.ts

support to the UI
**Issue Number:**
Fixes #
**Snapshots/Videos:**
**If relevant, did you update the documentation?**
**Summary**
**Does this PR introduce a breaking change?**
**Other information**
**Have you read the [contributing guide](https://github.com/caravan-bitcoin/caravan/blob/main/apps/coordinator/CONTRIBUTING.md)?**
**For information on creating and using changesets, please refer to our [documentation on changesets](https://github.com/caravan-bitcoin/caravan?tab=readme-ov-file#changesets)**.

Add regtest network support to coordinator

---

.changeset/few-rockets-drive.md
apps/coordinator/src/components/Wallet/TransactionPreview.jsx
packages/caravan-psbt/package.json

This isn't the best way to resolve this but the state management around transactions is sufficiently complex that I think this "quick and dirty" approach is probably, lowest code complexity to resolve the issue.
As we move the code to depend more on the unsignedPsbt value in the state as the source of truth, we need to make sure that it's "final" value is correct. Unfortunately when we create that value, we don't actually have all the info about _outputs_ that we need since the "change slice" hasn't been identified yet. This happens during tx preview but by that time the unsignedPsbt is set. This would result in signers not being able to identify change outputs from the PSBT. 
This simply does another "finalizeOutputs" once the change slice …

Change multisig

---

apps/coordinator/CONTRIBUTING.md

Add Troubleshooting in contribution readme to help with react pop errors and added discord channel link

Add Troubleshooting in contribution readme to help with react pop errors and added discord channel link
