caravan-bitcoin/caravan

.changeset/thirty-camels-think.md, README.md, apps/coordinator/README.md, apps/coordinator/src/components/ClientPicker/PrivateClientSettings.jsx, apps/coordinator/src/components/ErrorBoundary.tsx, apps/coordinator/src/components/Footer.tsx, apps/coordinator/src/components/Help.tsx, apps/coordinator/vite.config.ts
With the base url now being `caravan-bitcoin` it felt a little redundant to keep the base for the coordinator app still be `caravan`. This PR changes the base path to be `coordinator/#`. This works out of the box if you try and run locally with `turbo run dev` and then can access from `http://localhost:5173/coordinator/#/`. Hopefully if the automation is working, then when this gets released, it'll trigger a deploy to https://caravan-bitcoin.github.io/coordinator/#/
I also changed a bunch of other old urls referencing the old repo and the old unchained website.
=> Change coordinator base

.changeset/grumpy-flies-chew.md, .github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/release.yml, apps/coordinator/README.md, apps/coordinator/vite.config.ts, package.json
Deploy wasn't working as previously written. I was able to get the action to work if I copied the coordinator app's build directory to the root. Added a few other bits of polish including remote cacheing, only deploy on pushed tags to main, and made sure the release workflow pushed tags even for non-npm-published packages.
=> fix: deploy action, publish tags on release, and revert coordinator base

.changeset/calm-ligers-chew.md, apps/coordinator/Dockerfile, apps/coordinator/README.md, apps/coordinator/vite.config.ts
When trying to deploy caravan coordinator in environments other than github pages, the subpath causes some challenges. By making this conditional, caravan can be deployed without custom configuration in somewhere like vercel while still supporting github pages deployements. 
Now normal builds will simply be accessible from http://localhost:5173/# (no /caravan necessary). Same change for the docker deployment.
=> fix: conditional base url subpath for flexible deployments

apps/coordinator/vite.config.ts, package.json
Small change to make sure git sha is available in vercel deployments for the coordinator footer
=> use vercel environment variable as a fallback for git sha if available

.github/workflows/dockerhub.yml
1. Changes secret from `DOCKER_PASSWORD` to `DOCKER_TOKEN` because its actually an access token.
2. attempt to add the latest tag to `main` branch builds.
=> feat: add latest tag for main branch builds

.changeset/shaggy-vans-shave.md, packages/caravan-clients/src/client.test.ts, packages/caravan-clients/src/client.ts
Should resolve an issue where transactions couldn't broadcast with mempool.space.
Unclear how the api request body got twisted like this. Before the latest change to these lines, it was the same for both clients but in the way mempool.space was before this change. So they are now both the same again, but in the way fixed previously for blockstream (I did have a memory of actually fixing this before and I guess that's why).
=> fix: public client broadcast call

.github/workflows/deploy.yml, .github/workflows/dockerhub.yml
- github action should run only on caravan coordinator tags with an `@X.Y.Z` version
- change the image name to `caravanbitcoin/coordinator`, as `caravanbitcoin/caravan` felt redundant.
- Tags are versions, so `@1.0.0` would generate both `1.0.0` and `1.0`.  Also, a @1.0.1 version would generate a new `1.0.1` and update the `1.0`.
=> fix: better docker tags

apps/coordinator/package.json
Caravan coordinator is an app, not an npm package, so the @scope/package naming pattern isn't needed.  This will enable us to quickly identify on the https://github.com/caravan-bitcoin/caravan/releases which release is a package release, and which is an app release.
=> fix: descope coordinator app

.changeset/eleven-hairs-talk.md
Patch coordinator version so [@caravan/wallets@0.1.2](https://github.com/caravan-bitcoin/caravan/releases/tag/%40caravan%2Fwallets%400.1.2) and [@caravan/clients@0.0.3](https://github.com/caravan-bitcoin/caravan/releases/tag/%40caravan%2Fclients%400.0.3) are included.
=> fix: bump coordinator version

package.json
`changeset version` updates package.json, but not package-lock.json.
Changeset has an open issue for this, https://github.com/changesets/action/issues/203.  
A suggested workaround is to use `npm install`, https://github.com/changesets/action/issues/203#issuecomment-1460115073
=> Update version in package-lock on release

package.json, packages/caravan-psbt/README.md, packages/caravan-psbt/package.json, packages/caravan-psbt/src/psbtv2.ts
This change provides a readme covering the API as it currently sits for both the PSBT v0 and v2 packages. It also converts several code comments to act as conventional docstrings for use by IDEs.
=> Some initial documentation for the PSBT package

.changeset/fluffy-eyes-search.md, packages/caravan-psbt/src/psbtv2/functions.ts, packages/caravan-psbt/src/psbtv2/index.ts, packages/caravan-psbt/src/psbtv2/psbtv2.test.ts, packages/caravan-psbt/src/psbtv2/psbtv2.ts, packages/caravan-psbt/src/psbtv2/psbtv2maps.ts, packages/caravan-psbt/src/psbtv2/types.ts, packages/caravan-psbt/src/psbtv2/values.ts
This change should affect functionality in no way. This is purely a code organization refactor. PsbtV2 is given its own module directory to collect its related types into several categories by file:
- functions
- class psbtv2
- abstract psbtv2maps
- types
- values
=> refactor: split types among module categories creating room to grow

README.md
This PR adds a Docker badge to the repo's README.
[![Pulls from DockerHub](https://img.shields.io/docker/pulls/caravanbitcoin/coordinator?logo=docker)](https://hub.docker.com/r/caravanbitcoin/coordinator)
I love that you are publishing a Docker image, however it was nearly impossible to know there was a Docker image at all. I wanted to make sure I was using the Official image created from this open source repo. I looked through all the GitHub actions and found that it was publishing to 
https://hub.docker.com/r/caravanbitcoin/coordinator so I think it will be great for other user's to also see the Docker repo.
=> Add DockerHub icon

.changeset/cool-cows-learn.md, packages/caravan-psbt/README.md, packages/caravan-psbt/src/psbtv2/psbtv2.test.ts, packages/caravan-psbt/src/psbtv2/psbtv2.ts
This change adds several getter methods to PsbtV2 to support operator role validation:
-  `get isReadyForConstructor`
-  `get isReadyForUpdater`
-  `get isReadyForSigner`
-  `get isReadyForCombiner`
-  `get isReadyForInputFinalizer`
-  `get isReadyForTransactionExtractor`
These getters return `true` when the psbt is ready for actions by the role it is named after. `isReadyForInputFinalizer` has yet to be implemented. It is likely that the psbt may be ready for more than one role in any state.
These getters are used in a few public methods to validate that the psbt is ready for the role for which is responsible of the action. The methods will throw if the psbt is not ready for that role.
- `addInput`, `addOutput`, `deleteInput`, `deleteOutput`, and `dangerouslySetGlobalTxVersion1` checks …
=> Psbtv2 operator role validation

.changeset/funny-gorillas-destroy.md, .github/workflows/release.yml, package-lock.json, package.json, packages/multisig/package.json, turbo.json
when trying to install one of the new packages (psbt or wallets) that depends on the internal package `@caravan/multisig`, I'm getting an error that the package can't be found in the registry. This shouldn't even be attempted. I'm not sure that this will fix it, but when looking at some turborepo examples, I did see that [internal packages](https://github.com/vercel/turbo/blob/main/examples/kitchen-sink/packages/logger/package.json) seem to have a version of `0.0.0` so maybe that will help. Included some other cleanup in the build processes that may or may not be related.
=> fix: some build cleanup to avoid dependency

.changeset/mighty-spiders-matter.md
Bump coordinator version so it includes [@caravan/wallets@0.2.2](https://github.com/caravan-bitcoin/caravan/releases/tag/%40caravan%2Fwallets%400.2.2) and [@caravan/psbt@1.3.2](https://github.com/caravan-bitcoin/caravan/releases/tag/%40caravan%2Fpsbt%401.3.2).
=> Chore: bump coordinator

.changeset/seven-keys-matter.md, packages/caravan-psbt/src/psbtv0/psbt.ts
Unclear to me why this wasn't picked up in the CI with #104, but this should fix an error when caravan/wallets or caravan/psbt are installed externally from the monorepo
=> specify direct import

.changeset/thirty-dolls-type.md, packages/caravan-psbt/src/psbtv0/utils.ts
Fixes a regression in which PSBTs could not be signed in indirect keystore interactions due to a missing redeem script. 
[Introduced](https://github.com/caravan-bitcoin/caravan/commit/0d81717fade918ec337093e3dc4c3862662d20c3#diff-12369fc70a2ad8c599734fefe86246c867a701f3b5bda04eb964e56b822c2a25R137) in #91
=> fix: multisig support for indirect keystore interactions

.changeset/heavy-kids-confess.md, apps/coordinator/src/actions/keystoreActions.ts, apps/coordinator/src/components/CreateAddress/HardwareWalletPublicKeyImporter.jsx, apps/coordinator/src/components/CreateAddress/PublicKeyImporter.jsx, apps/coordinator/src/components/RegisterWallet/RegisterBitBoxButton.jsx, apps/coordinator/src/components/RegisterWallet/index.jsx, apps/coordinator/src/components/ScriptExplorer/SignatureImporter.jsx, apps/coordinator/src/components/Slices/ConfirmAddress.jsx, apps/coordinator/src/components/TestSuiteRun/KeystorePicker.tsx, apps/coordinator/src/components/TestSuiteRun/TestSuiteRunSummary.tsx, apps/coordinator/src/components/Wallet/ExtendedPublicKeyImporter.jsx, apps/coordinator/src/components/Wallet/RegisterWallet.jsx, apps/coordinator/src/components/Wallet/index.jsx, apps/coordinator/src/tests/bitbox.js, apps/coordinator/src/tests/index.js, apps/coordinator/src/tests/registration.jsx, apps/coordinator/src/tests/signing.jsx, apps/coordinator/vite.config.ts, package-lock.json, packages/caravan-wallets/package.json, packages/caravan-wallets/src/bitbox.ts, packages/caravan-wallets/src/index.ts, packages/caravan-wallets/tsconfig.json, packages/caravan-wallets/tsup.config.ts
Using the `bitbox-api` NPM package, which loads a WASM module.
Note about CJS:
Currently the `bitbox-api` package is an ESM package with a `module: ...` entrypoint, so it is not compatible with the `cjs` target of caravan-wallets. The only workaround that I could find where compilation succeeds and the package works in the browser is to mark bitbox-api as external in tsup.config.ts.
Note about signing tests:
- The BitBox02 requires the previous transaction of each input to be
present in the PSBT (`PSBT_IN_NON_WITNESS_UTXO`), so it can verify the
input amount and avoid fee attacks. The signing test fixtures are
missing these, so they fail.
- The BitBox02 uses the anti-klepto (anti-exfil) protocol to mitigate
covert nonce exfil attacks. This results in random signatures. The
unit test …
=> add support for the BitBox02 hardware wallet

.changeset/shy-dogs-wonder.md, apps/coordinator/src/components/ScriptExplorer/DirectSignatureImporter.jsx, package-lock.json, packages/caravan-psbt/package.json, packages/caravan-psbt/src/psbtv0/psbt.test.ts, packages/caravan-psbt/src/psbtv0/psbt.ts, turbo.json
With this fix, ledger and trezor device interactions should be able to translate PSBTs directly into the signing interaction. Previously this only was supported for P2SH and segwit required the specialized input and output objects.
=> Translate segwit psbt

.changeset/thick-clouds-run.md, packages/caravan-wallets/tsup.config.ts
When attempting to use caravan/wallets in an external application to leverage the fix that went out with #147 I was finding that the older external dependency was being used. 
There were two options I could come up with to resolve this. One was to pin the version for internal dependencies in the caravan/wallets package.json. This felt like it lost many of the benefits of working in a monorepo environment. The other was to bundle the internal dependency with the final production bundle. Since we bundle with tsup, we can use the noExternal config to take care of this.
Long term this feels like the cleaner pattern and we'll probably want to do this across the packages that we publish.
=> fix(wallets): bundle internal dependencies with production bundle

.changeset/stupid-starfishes-taste.md, packages/caravan-wallets/src/coldcard.ts, packages/caravan-wallets/src/custom.ts
Checks for REGTEST network in Coldcard and Custom interactions rather than throwing "Unknown network"
=> fix: unknown network error for regtest

turbo.json
I noticed that after making the change in https://github.com/caravan-bitcoin/caravan/commit/5c3c456d78e8ab017cb960027d316cff98dc3ca2 turbo.json needed to define build as a dependency for dev tasks since the `noExternal` dep would need to be pre-built and bundled. I noticed this was breaking when trying to run `npm run dev` fresh.
=> fix: turbo dev depends on build w/ esbuild noExternal

package-lock.json
The package-lock got out of sync from a dependabot merge.
=> chore: update package-lock to match package.json

.github/workflows/ci.yml, .github/workflows/deploy.yml
The use of `npm install` over `npm ci` allowed package-lock.json problems to be missed in the PR build. 
- [Release #133](https://github.com/caravan-bitcoin/caravan/actions/runs/12788151852)
- [Release #134](https://github.com/caravan-bitcoin/caravan/actions/runs/12938217541)
=> fix: replace npm install with npm ci in CI workflows

.changeset/two-files-relate.md, apps/coordinator/package.json, apps/coordinator/src/reducers/transactionReducer.test.js, package-lock.json, packages/caravan-psbt/package.json, packages/caravan-psbt/tsup.config.ts
I tried to do the noExternal fix that we do in caravan/wallets but unfortunately trying to pre-bundle caravan/bitcoin caused all sorts of issues (as far as I can tell most of those revolve around the pre-bundling of bitcoinjs-lib). I think I had the same issue trying to pre-bundle caravan-bitcoin in caravan-wallets too. 
This should resolve the issue. It just means it makes testing and developing in caravan/psbt more complex if we need to make changes in in caravan-bitcoin.
=> fix(psbt): lock dependency of caravan-bitcoin

turbo.json
This resolved the error thrown when running `npm ci && npm run version`, as is run during the release action.
Error:
```
│ /GitHub/caravan/apps/coordinator/src/actions/keystoreActions.ts
│   1:58  error  Unable to resolve path to module '@caravan/wallets'  import/no-unresolved
│ 
│ /GitHub/caravan/apps/coordinator/src/components/Coldcard/ColdcardExtendedPublicKeyImpor
│ ter.jsx
│   3:26  error  Unable to resolve path to module '@caravan/wallets'  import/no-unresolved
```
=> chore(turbo): add build as lint task dependency

.changeset/nice-cherries-remain.md, packages/caravan-psbt/src/psbtv2/psbtv2.test.ts, packages/caravan-psbt/src/psbtv2/psbtv2.ts
This change is to help with compatibility when converting between psbt versions. `PsbtV2.FromV0()` has an option to create a PSBTv2 forceably setting the `PSBT_GLOBAL_TX_VERSION` field to 1. This is a bip370 non-compliant psbtv2, but it was presumably added for compatibility reasons when converting from v0.
A `PsbtV2` class created in such a way can be serialized with `PsbtV2.serialize()`, however, the resultant serialized psbt cannot be used to re-instantiate a `PsbtV2`. This change relaxes the Txnv2 requirement so that these exception case serialized psbts can be passed back into the constructor.
It should be carefully noted that this change might imply a dangerous use for a PSBTv2. The bip370 specifies that the txn v2 requirement was added to simplify the negotiation of validation …
=> Allow a PsbtV2 to be constructed with a psbtv2 which has been forceably set to have PSBT_GLOBAL_TX_VERSION === 1

.changeset/lucky-onions-promise.md, packages/caravan-psbt/provide-self.ts, packages/caravan-psbt/tsup.config.ts
Adds an ESBuild plugin that prepends every JS build artifact with a slap dash declaration of self so that problematic but inconsequential browser only code doesn't break server side use.
=> An admittedly hack-y fix for using @caravan/psbt on the server side.

package-lock.json, packages/multisig/jest.config.js, packages/multisig/package.json
- Removed Jest-related dependencies:
- jest
- ts-jest
- jsdom
- @types/jest
- Added Vitest dependency
- Updated test scripts in package.json:
- Changed `test` to use `vitest --watch=false src`
- Changed `test:watch` to use `vitest --watch src`
- Removed `test:debug` as it's no longer needed
- All 6 tests are passing with Vitest
- No changes needed to test logic as it was already compatible with Vitest
- Reduces package dependencies
- Aligns with project's move towards Vitest
- Simplifies test configuration
- Maintains existing test coverage and functionality
- The migration was straightforward as the test file was already using modern test syntax
- No changes were needed to the test logic itself
- The package's minimal test dependencies made the migration process simpler
- Part of the …
=> [Test]: Jest to Vitest migration `multisig` package 

.changeset/wise-ads-invent.md, packages/caravan-wallets/src/policy.test.ts, packages/caravan-wallets/src/policy.ts
Small change to support converting a key origin descriptor string into a key origin object.
=> feat(wallets): policy from string conversion

apps/coordinator/package.json, apps/coordinator/vite.config.ts, package-lock.json, package.json, packages/caravan-bitcoin/tsup.config.ts, packages/caravan-wallets/tsup.config.ts
Turns out the dev command was broken when the build deps were upgraded. There were some conflicts with the older version of vite. Needed to upgrade vite and relevant plugins and for some reason needed to move some deps out of coordinator and into root.
=> fix: some missing buffer polyfills

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Hi, I’ve added a ``PULL_REQUEST_TEMPLATE.md`` file to the  ``.github`` directory to help standardize pull request submissions and make the contribution process smoother for everyone. The template includes sections for change type, issue number, snapshots, documentation updates, and a checklist to ensure high-quality PRs.
**Why this could be helpful:**
The template will guide contributors to provide essential details like the type of change, related issues, media evidence (screenshots/videos), documentation updates, and testing status, making it easier for maintainers to review and merge changes efficiently.
Please review and let me know any feedback or suggestions,  I'm happy to make adjustments as needed
=> Added contribution templates to streamline PRs and issue reporting

.changeset/long-chicken-lie.md, apps/coordinator/src/actions/transactionActions.js, apps/coordinator/src/components/Wallet/TransactionPreview.jsx, apps/coordinator/src/components/Wallet/WalletSpend.jsx, apps/coordinator/src/selectors/transaction.ts, apps/coordinator/src/utils/psbtUtils.ts
Feature Added – Fixes the issue where importing a partially signed PSBT would not retain the existing partial signatures.
---
Fixes #162 – *Import PSBT is not importing partial signatures*
---
1. Create an unsigned PSBT in Caravan and download it.
2. Sign it outside Caravan using a compatible wallet/tool.
3. Re-import the wallet config and go to **Send > Import PSBT**.
4. Import the partially signed PSBT.
5. ❌ Observe: The partial signatures are not reflected, and Caravan treats it as unsigned.
---
* **Core Fix**: Caravan previously failed to recognize and import partial signatures when reloading a PSBT. This PR introduces the necessary logic to parse and preserve those signatures correctly.
* **UI Enhancement**: Updated the Import PSBT flow to give visual feedback when signatures are …
=> Import Partially Signed PSBT works now 

.changeset/old-boats-train.md, apps/coordinator/package.json, apps/coordinator/src/components/ScriptExplorer/DustChip.tsx, apps/coordinator/src/components/ScriptExplorer/UTXOSet.jsx
This PR introduces a new DustChip component that classifies a UTXO amount as either:
Dust (too small to spend economically),
Warning (borderline wasteful), or
Economical
It uses WasteMetrics from @caravan/health to calculate dynamic dust thresholds based on:
The current feeRate
walletConfig (script type + quorum settings)
✅ Features
Supports custom tooltip via tooltipText prop
Falls back to default descriptions when no tooltip is provided
=>  Dustchip | Dustchip file added on UI

apps/coordinator/src/clients/transactions.ts, apps/coordinator/src/components/Wallet/TransactionsTab/FeeBumping/utils.ts, apps/coordinator/src/hooks/utxos.ts
Non-user facing change but I found that the current setup for fetching tx input coins was causing infinite re-renders when working on #338. This extracts one of the calls out of a hook so that it can be more effectively memoized, thus avoiding the re-renders. I tested this change out in #338 already and confirmed it works.
=> fixes utxo extraction hooks to avoid infinite re-renders

.changeset/young-falcons-build.md, packages/caravan-fees/src/cpfp.ts, packages/caravan-fees/src/tests/cpfp.fixtures.ts, packages/caravan-fees/src/tests/cpfp.test.ts, packages/caravan-fees/src/tests/psbtTestCpfp.fixtures.ts, packages/caravan-fees/src/tests/psbtTestCpfp.test.ts, packages/caravan-fees/src/types.ts
Patch - Added parentUtxo parameter to CPFP transaction creation
**Issue Number:**
Fixes N/A
**Snapshots/Videos:**
N/A -
**If relevant, did you update the documentation?**
Updated TSDoc comments in the createCPFPTransaction function and CPFPOptions interface
**Summary**
**Problem:** 
The existing CPFP implementation in `@caravan/fees` had a critical limitation - it attempted to create a basic UTXO from the parent transaction output using only `createOutputScript()`, but this approach was missing essential PSBT metadata required for proper multisig transaction signing (witnessScript, redeemScript, bip32Derivations, etc.).
**Solution:**
- Modified `CPFPOptions` interface to require a `parentUtxo` parameter with complete PSBT metadata
- Updated …
=>  Added parentUtxo parameter to `createCPFPTransaction`
